------------------------------------
Can we throw multiple exceptions?
------------------------------------
	** throw_multiple_exceptions()

When the first exception is thrown, i.e.,
NullPointerException
the control moves on to find the relevant catch. If it is not found, the control moves to the
finally
clause if there is one.

Because of this, the control will never be able to reach the second statement/exception (i.e.,
ArithmeticException
), making it unreachable.

---------------------------------------------------------------
Can multiple catch clauses with any exception be in any order?
---------------------------------------------------------------
If there are exceptions that are related in an IS-A relationship, then the hierarchy would be followed by the child-on-top to parent-on-bottom.

Multiple exceptions can also be caught in a single catch clause using the pipe, |, operator.

---------------------------
Nested try-catch clauses
---------------------------
  ** nested_try_catch()

In the code above, the division of a/b causes an ArithmeticException, which is caught by the inside catch clause. 
In the case of the exception thrown, not handled, the outer catch clause will catch it.

Note: 
1) The use of finally is optional.
2) Exceptions can also be thrown inside the catch clause.
3) The finally block is a block that will be executed whether or not the exception is thrown/handled. It is useful to release resources, close connections, or close files.
4) Yes, this is legal try can be followed by finally without a catch block
